---
title: Jekyll Heroku Starter Kit
timezone: Africa/Johannesburg
locale: en_ZA
# url: 
# baseurl:
theme: jekyll-theme-minimal
exclude:
- '.bundle'
- '.github'
- '_site'
- 'vendor'
- '_config.yml'
- '.gitignore'
- 'CHANGELOG.md'
- 'CODE_OF_CONDUCT.md'
- 'config.ru'
- 'CONTRIBUTING.md'
- 'Gemfile'
- 'Gemfile.lock'
- 'LICENSE'
- 'Procfile'
- 'Rakefile'
- 'README.md'
- 'starter-kit.code-workspace'
- 'static.json'
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
---
