---
title: 22 Digital Agency Redirect
timezone: Africa/Johannesburg
locale: en_ZA
# url: https://22digital.agency/
# theme: jekyll-theme-minimal
exclude:
- '.bundle'
- '.github'
- '_site'
- 'vendor'
- '_config.yml'
- '.gitignore'
- 'CHANGELOG.md'
- 'CODE_OF_CONDUCT.md'
- 'config.ru'
- 'CONTRIBUTING.md'
- 'Gemfile'
- 'Gemfile.lock'
- 'LICENSE'
- 'Procfile'
- 'Rakefile'
- 'README.md'
- 'starter-kit.code-workspace'
- 'static.json'
plugins:
- jekyll-redirect-from
---
