---
title: Jekyll Heroku Starter Kit
description: Minimum boilerplate code for setting up and running a Jekyll site on Heroku.
timezone: Africa/Johannesburg
locale: en_ZA
# url: 
# baseurl:
logo: https://via.placeholder.com/250x100.png/E8117F/fff?text=Logo+Placeholder
show_downloads: true
google_analytics: UA-100937492-4
theme: jekyll-theme-minimal
exclude:
- '_site'
- '.bundle'
- '.github'
- '.sass-cache'
- 'vendor'
- '_config.yml'
- '.gitignore'
- 'CHANGELOG.md'
- 'CODE_OF_CONDUCT.md'
- 'config.ru'
- 'CONTRIBUTING.md'
- 'Gemfile'
- 'Gemfile.lock'
- 'LICENSE'
- 'Procfile'
- 'Rakefile'
- 'README.md'
- 'starter-kit.code-workspace'
- 'static.json'
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate-v2
- jekyll-include-cache
- jekyll-last-modified-at
- jekyll-redirect-from
---
